version: "3.8"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - VITE_PORT=3000 
    command: ["sh", "-c", "while ! nc -z backend 5000; do sleep 1; done && npm run dev -- --host --port 3000"]
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    working_dir: /app
    tty: true
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=LeadManagementDb;User Id=sa;Password=Admin@123;"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  frontend-tests:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    command: ["npm", "test", "--", "--run"]

  backend-tests:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    command: ["dotnet", "test"]



